var move = function(name, pp, gen) {
    this.name = name;
    this.pp = pp;
    this.gen = gen;
};

var moves = [
    new move("empty slot", 0, 3),
    new move("Pound", 35, 3),
    new move("Karate Chop", 25, 3),
    new move("Double Slap", 10, 3),
    new move("Comet Punch", 15, 3),
    new move("Mega Punch", 20, 3),
    new move("Pay Day", 20, 3),
    new move("Fire Punch", 15, 3),
    new move("Ice Punch", 15, 3),
    new move("Thunder Punch", 15, 3),
    new move("Scratch", 35, 3),
    new move("Vice Grip", 30, 3),
    new move("Guillotine", 5, 3),
    new move("Razor Wind", 10, 3),
    new move("Swords Dance", 30, 3),
    new move("Cut", 30, 3),
    new move("Gust", 35, 3),
    new move("Wing Attack", 35, 3),
    new move("Whirlwind", 20, 3),
    new move("Fly", 15, 3),
    new move("Bind", 20, 3),
    new move("Slam", 20, 3),
    new move("Vine Whip", 10, 3),
    new move("Stomp", 20, 3),
    new move("Double Kick", 30, 3),
    new move("Mega Kick", 5, 3),
    new move("Jump Kick", 25, 3),
    new move("Rolling Kick", 15, 3),
    new move("Sand Attack", 15, 3),
    new move("Headbutt", 15, 3),
    new move("Horn Attack", 25, 3),
    new move("Fury Attack", 20, 3),
    new move("Horn Drill", 5, 3),
    new move("Tackle", 35, 3),
    new move("Body Slam", 15, 3),
    new move("Wrap", 20, 3),
    new move("Take Down", 20, 3),
    new move("Thrash", 20, 3),
    new move("Double-Edge", 15, 3),
    new move("Tail Whip", 30, 3),
    new move("Poison Sting", 35, 3),
    new move("Twineedle", 20, 3),
    new move("Pin Missile", 20, 3),
    new move("Leer", 30, 3),
    new move("Bite", 25, 3),
    new move("Growl", 40, 3),
    new move("Roar", 20, 3),
    new move("Sing", 15, 3),
    new move("Supersonic", 20, 3),
    new move("Sonic Boom", 20, 3),
    new move("Disable", 20, 3),
    new move("Acid", 30, 3),
    new move("Ember", 25, 3),
    new move("Flamethrower", 15, 3),
    new move("Mist", 30, 3),
    new move("Water Gun", 25, 3),
    new move("Hydro Pump", 5, 3),
    new move("Surf", 15, 3),
    new move("Ice Beam", 10, 3),
    new move("Blizzard", 5, 3),
    new move("Psybeam", 20, 3),
    new move("Bubble Beam", 20, 3),
    new move("Aurora Beam", 20, 3),
    new move("Hyper Beam", 5, 3),
    new move("Peck", 35, 3),
    new move("Drill Peck", 20, 3),
    new move("Submission", 25, 3),
    new move("Low Kick", 20, 3),
    new move("Counter", 20, 3),
    new move("Seismic Toss", 20, 3),
    new move("Strength", 15, 3),
    new move("Absorb", 20, 3),
    new move("Mega Drain", 10, 3),
    new move("Leech Seed", 10, 3),
    new move("Growth", 40, 3),
    new move("Razor Leaf", 25, 3),
    new move("Solar Beam", 10, 3),
    new move("Poison Powder", 35, 3),
    new move("Stun Spore", 30, 3),
    new move("Sleep Powder", 15, 3),
    new move("Petal Dance", 20, 3),
    new move("String Shot", 40, 3),
    new move("Dragon Rage", 10, 3),
    new move("Fire Spin", 15, 3),
    new move("Thunder Shock", 30, 3),
    new move("Thunderbolt", 15, 3),
    new move("Thunder Wave", 20, 3),
    new move("Thunder", 10, 3),
    new move("Rock Throw", 15, 3),
    new move("Earthquake", 10, 3),
    new move("Fissure", 5, 3),
    new move("Dig", 10, 3),
    new move("Toxic", 10, 3),
    new move("Confusion", 25, 3),
    new move("Psychic", 10, 3),
    new move("Hypnosis", 20, 3),
    new move("Meditate", 40, 3),
    new move("Agility", 30, 3),
    new move("Quick Attack", 30, 3),
    new move("Rage", 20, 3),
    new move("Teleport", 20, 3),
    new move("Night Shade", 15, 3),
    new move("Mimic", 10, 3),
    new move("Screech", 40, 3),
    new move("Double Team", 15, 3),
    new move("Recover", 20, 3),
    new move("Harden", 30, 3),
    new move("Minimize", 20, 3),
    new move("Smokescreen", 20, 3),
    new move("Confuse Ray", 10, 3),
    new move("Withdraw", 40, 3),
    new move("Defense Curl", 40, 3),
    new move("Barrier", 30, 3),
    new move("Light Screen", 30, 3),
    new move("Haze", 30, 3),
    new move("Reflect", 20, 3),
    new move("Focus Energy", 30, 3),
    new move("Bide", 10, 3),
    new move("Metronome", 10, 3),
    new move("Mirror Move", 20, 3),
    new move("Self-Destruct", 5, 3),
    new move("Egg Bomb", 10, 3),
    new move("Lick", 30, 3),
    new move("Smog", 20, 3),
    new move("Sludge", 20, 3),
    new move("Bone Club", 20, 3),
    new move("Fire Blast", 5, 3),
    new move("Waterfall", 15, 3),
    new move("Clamp", 10, 3),
    new move("Swift", 20, 3),
    new move("Skull Bash", 15, 3),
    new move("Spike Cannon", 15, 3),
    new move("Constrict", 35, 3),
    new move("Amnesia", 20, 3),
    new move("Kinesis", 15, 3),
    new move("Soft-Boiled", 10, 3),
    new move("High Jump Kick", 20, 3),
    new move("Glare", 30, 3),
    new move("Dream Eater", 15, 3),
    new move("Poison Gas", 40, 3),
    new move("Barrage", 20, 3),
    new move("Leech Life", 15, 3),
    new move("Lovely Kiss", 10, 3),
    new move("Sky Attack", 5, 3),
    new move("Transform", 10, 3),
    new move("Bubble", 30, 3),
    new move("Dizzy Punch", 10, 3),
    new move("Spore", 15, 3),
    new move("Flash", 20, 3),
    new move("Psywave", 15, 3),
    new move("Splash", 40, 3),
    new move("Acid Armor", 40, 3),
    new move("Crabhammer", 10, 3),
    new move("Explosion", 5, 3),
    new move("Fury Swipes", 15, 3),
    new move("Bonemerang", 10, 3),
    new move("Rest", 10, 3),
    new move("Rock Slide", 10, 3),
    new move("Hyper Fang", 15, 3),
    new move("Sharpen", 30, 3),
    new move("Conversion", 30, 3),
    new move("Tri Attack", 10, 3),
    new move("Super Fang", 10, 3),
    new move("Slash", 20, 3),
    new move("Substitute", 10, 3),
    new move("Struggle", 1, 3),
    new move("Sketch", 1, 3),
    new move("Triple Kick", 10, 3),
    new move("Thief", 10, 3),
    new move("Spider Web", 10, 3),
    new move("Mind Reader", 5, 3),
    new move("Nightmare", 15, 3),
    new move("Flame Wheel", 25, 3),
    new move("Snore", 15, 3),
    new move("Curse", 10, 3),
    new move("Flail", 15, 3),
    new move("Conversion 2", 30, 3),
    new move("Aeroblast", 5, 3),
    new move("Cotton Spore", 40, 3),
    new move("Reversal", 15, 3),
    new move("Spite", 10, 3),
    new move("Powder Snow", 25, 3),
    new move("Protect", 10, 3),
    new move("Mach Punch", 30, 3),
    new move("Scary Face", 10, 3),
    new move("Feint Attack", 20, 3),
    new move("Sweet Kiss", 10, 3),
    new move("Belly Drum", 10, 3),
    new move("Sludge Bomb", 10, 3),
    new move("Mud-Slap", 10, 3),
    new move("Octazooka", 10, 3),
    new move("Spikes", 20, 3),
    new move("Zap Cannon", 5, 3),
    new move("Foresight", 40, 3),
    new move("Destiny Bond", 5, 3),
    new move("Perish Song", 5, 3),
    new move("Icy Wind", 15, 3),
    new move("Detect", 5, 3),
    new move("Bone Rush", 10, 3),
    new move("Lock-On", 5, 3),
    new move("Outrage", 15, 3),
    new move("Sandstorm", 10, 3),
    new move("Giga Drain", 5, 3),
    new move("Endure", 10, 3),
    new move("Charm", 20, 3),
    new move("Rollout", 20, 3),
    new move("False Swipe", 40, 3),
    new move("Swagger", 15, 3),
    new move("Milk Drink", 10, 3),
    new move("Spark", 20, 3),
    new move("Fury Cutter", 20, 3),
    new move("Steel Wing", 25, 3),
    new move("Mean Look", 5, 3),
    new move("Attract", 15, 3),
    new move("Sleep Talk", 10, 3),
    new move("Heal Bell", 5, 3),
    new move("Return", 20, 3),
    new move("Present", 15, 3),
    new move("Frustration", 20, 3),
    new move("Safeguard", 25, 3),
    new move("Pain Split", 20, 3),
    new move("Sacred Fire", 5, 3),
    new move("Magnitude", 30, 3),
    new move("Dynamic Punch", 5, 3),
    new move("Megahorn", 10, 3),
    new move("Dragon Breath", 20, 3),
    new move("Baton Pass", 40, 3),
    new move("Encore", 5, 3),
    new move("Pursuit", 20, 3),
    new move("Rapid Spin", 40, 3),
    new move("Sweet Scent", 20, 3),
    new move("Iron Tail", 15, 3),
    new move("Metal Claw", 35, 3),
    new move("Vital Throw", 10, 3),
    new move("Morning Sun", 5, 3),
    new move("Synthesis", 5, 3),
    new move("Moonlight", 5, 3),
    new move("Hidden Power", 15, 3),
    new move("Cross Chop", 5, 3),
    new move("Twister", 20, 3),
    new move("Rain Dance", 5, 3),
    new move("Sunny Day", 5, 3),
    new move("Crunch", 15, 3),
    new move("Mirror Coat", 20, 3),
    new move("Psych Up", 10, 3),
    new move("Extreme Speed", 5, 3),
    new move("Ancient Power", 5, 3),
    new move("Shadow Ball", 15, 3),
    new move("Future Sight", 15, 3),
    new move("Rock Smash", 15, 3),
    new move("Whirlpool", 15, 3),
    new move("Beat Up", 10, 3),
    new move("Fake Out", 10, 3),
    new move("Uproar", 10, 3),
    new move("Stockpile", 10, 3),
    new move("Spit Up", 10, 3),
    new move("Swallow", 10, 3),
    new move("Heat Wave", 10, 3),
    new move("Hail", 10, 3),
    new move("Torment", 15, 3),
    new move("Flatter", 15, 3),
    new move("Will-O-Wisp", 15, 3),
    new move("Memento", 10, 3),
    new move("Facade", 20, 3),
    new move("Focus Punch", 20, 3),
    new move("Smelling Salts", 10, 3),
    new move("Follow Me", 20, 3),
    new move("Nature Power", 20, 3),
    new move("Charge", 20, 3),
    new move("Taunt", 20, 3),
    new move("Helping Hand", 20, 3),
    new move("Trick", 10, 3),
    new move("Role Play", 10, 3),
    new move("Wish", 10, 3),
    new move("Assist", 20, 3),
    new move("Ingrain", 20, 3),
    new move("Superpower", 5, 3),
    new move("Magic Coat", 15, 3),
    new move("Recycle", 10, 3),
    new move("Revenge", 10, 3),
    new move("Brick Break", 15, 3),
    new move("Yawn", 10, 3),
    new move("Knock Off", 20, 3),
    new move("Endeavor", 5, 3),
    new move("Eruption", 5, 3),
    new move("Skill Swap", 10, 3),
    new move("Imprison", 10, 3),
    new move("Refresh", 20, 3),
    new move("Grudge", 5, 3),
    new move("Snatch", 10, 3),
    new move("Secret Power", 20, 3),
    new move("Dive", 10, 3),
    new move("Arm Thrust", 20, 3),
    new move("Camouflage", 20, 3),
    new move("Tail Glow", 20, 3),
    new move("Luster Purge", 5, 3),
    new move("Mist Ball", 5, 3),
    new move("Feather Dance", 15, 3),
    new move("Teeter Dance", 20, 3),
    new move("Blaze Kick", 10, 3),
    new move("Mud Sport", 15, 3),
    new move("Ice Ball", 20, 3),
    new move("Needle Arm", 15, 3),
    new move("Slack Off", 10, 3),
    new move("Hyper Voice", 10, 3),
    new move("Poison Fang", 15, 3),
    new move("Crush Claw", 10, 3),
    new move("Blast Burn", 5, 3),
    new move("Hydro Cannon", 5, 3),
    new move("Meteor Mash", 10, 3),
    new move("Astonish", 15, 3),
    new move("Weather Ball", 10, 3),
    new move("Aromatherapy", 5, 3),
    new move("Fake Tears", 20, 3),
    new move("Air Cutter", 25, 3),
    new move("Overheat", 5, 3),
    new move("Odor Sleuth", 40, 3),
    new move("Rock Tomb", 10, 3),
    new move("Silver Wind", 5, 3),
    new move("Metal Sound", 40, 3),
    new move("Grass Whistle", 15, 3),
    new move("Tickle", 20, 3),
    new move("Cosmic Power", 20, 3),
    new move("Water Spout", 5, 3),
    new move("Signal Beam", 15, 3),
    new move("Shadow Punch", 20, 3),
    new move("Extrasensory", 30, 3),
    new move("Sky Uppercut", 15, 3),
    new move("Sand Tomb", 15, 3),
    new move("Sheer Cold", 5, 3),
    new move("Muddy Water", 10, 3),
    new move("Bullet Seed", 30, 3),
    new move("Aerial Ace", 20, 3),
    new move("Icicle Spear", 30, 3),
    new move("Iron Defense", 15, 3),
    new move("Block", 5, 3),
    new move("Howl", 40, 3),
    new move("Dragon Claw", 15, 3),
    new move("Frenzy Plant", 5, 3),
    new move("Bulk Up", 20, 3),
    new move("Bounce", 5, 3),
    new move("Mud Shot", 15, 3),
    new move("Poison Tail", 25, 3),
    new move("Covet", 40, 3),
    new move("Volt Tackle", 15, 3),
    new move("Magical Leaf", 20, 3),
    new move("Water Sport", 15, 3),
    new move("Calm Mind", 20, 3),
    new move("Leaf Blade", 15, 3),
    new move("Dragon Dance", 20, 3),
    new move("Rock Blast", 10, 3),
    new move("Shock Wave", 20, 3),
    new move("Water Pulse", 20, 3),
    new move("Doom Desire", 5, 3),
    new move("Psycho Boost", 5, 3),
    new move("Roost", 10, 4),
    new move("Gravity", 5, 4),
    new move("Miracle Eye", 40, 4),
    new move("Wake-Up Slap", 10, 4),
    new move("Hammer Arm", 10, 4),
    new move("Gyro Ball", 5, 4),
    new move("Healing Wish", 10, 4),
    new move("Brine", 10, 4),
    new move("Natural Gift", 15, 4),
    new move("Feint", 10, 4),
    new move("Pluck", 20, 4),
    new move("Tailwind", 30, 4),
    new move("Acupressure", 30, 4),
    new move("Metal Burst", 10, 4),
    new move("U-turn", 20, 4),
    new move("Close Combat", 5, 4),
    new move("Payback", 10, 4),
    new move("Assurance", 10, 4),
    new move("Embargo", 15, 4),
    new move("Fling", 10, 4),
    new move("Psycho Shift", 10, 4),
    new move("Trump Card", 5, 4),
    new move("Heal Block", 15, 4),
    new move("Wring Out", 5, 4),
    new move("Power Trick", 10, 4),
    new move("Gastro Acid", 10, 4),
    new move("Lucky Chant", 30, 4),
    new move("Me First", 20, 4),
    new move("Copycat", 20, 4),
    new move("Power Swap", 10, 4),
    new move("Guard Swap", 10, 4),
    new move("Punishment", 5, 4),
    new move("Last Resort", 5, 4),
    new move("Worry Seed", 10, 4),
    new move("Sucker Punch", 5, 4),
    new move("Toxic Spikes", 20, 4),
    new move("Heart Swap", 10, 4),
    new move("Aqua Ring", 20, 4),
    new move("Magnet Rise", 10, 4),
    new move("Flare Blitz", 15, 4),
    new move("Force Palm", 10, 4),
    new move("Aura Sphere", 20, 4),
    new move("Rock Polish", 20, 4),
    new move("Poison Jab", 20, 4),
    new move("Dark Pulse", 15, 4),
    new move("Night Slash", 15, 4),
    new move("Aqua Tail", 10, 4),
    new move("Seed Bomb", 15, 4),
    new move("Air Slash", 20, 4),
    new move("X-Scissor", 15, 4),
    new move("Bug Buzz", 10, 4),
    new move("Dragon Pulse", 10, 4),
    new move("Dragon Rush", 10, 4),
    new move("Power Gem", 20, 4),
    new move("Drain Punch", 5, 4),
    new move("Vacuum Wave", 30, 4),
    new move("Focus Blast", 5, 4),
    new move("Energy Ball", 10, 4),
    new move("Brave Bird", 15, 4),
    new move("Earth Power", 10, 4),
    new move("Switcheroo", 10, 4),
    new move("Giga Impact", 5, 4),
    new move("Nasty Plot", 20, 4),
    new move("Bullet Punch", 30, 4),
    new move("Avalanche", 10, 4),
    new move("Ice Shard", 30, 4),
    new move("Shadow Claw", 15, 4),
    new move("Thunder Fang", 15, 4),
    new move("Ice Fang", 15, 4),
    new move("Fire Fang", 15, 4),
    new move("Shadow Sneak", 30, 4),
    new move("Mud Bomb", 10, 4),
    new move("Psycho Cut", 20, 4),
    new move("Zen Headbutt", 15, 4),
    new move("Mirror Shot", 10, 4),
    new move("Flash Cannon", 10, 4),
    new move("Rock Climb", 20, 4),
    new move("Defog", 15, 4),
    new move("Trick Room", 5, 4),
    new move("Draco Meteor", 5, 4),
    new move("Discharge", 15, 4),
    new move("Lava Plume", 15, 4),
    new move("Leaf Storm", 5, 4),
    new move("Power Whip", 10, 4),
    new move("Rock Wrecker", 5, 4),
    new move("Cross Poison", 20, 4),
    new move("Gunk Shot", 5, 4),
    new move("Iron Head", 15, 4),
    new move("Magnet Bomb", 20, 4),
    new move("Stone Edge", 5, 4),
    new move("Captivate", 20, 4),
    new move("Stealth Rock", 20, 4),
    new move("Grass Knot", 20, 4),
    new move("Chatter", 20, 4),
    new move("Judgment", 10, 4),
    new move("Bug Bite", 20, 4),
    new move("Charge Beam", 10, 4),
    new move("Wood Hammer", 15, 4),
    new move("Aqua Jet", 20, 4),
    new move("Attack Order", 15, 4),
    new move("Defend Order", 10, 4),
    new move("Heal Order", 10, 4),
    new move("Head Smash", 5, 4),
    new move("Double Hit", 10, 4),
    new move("Roar of Time", 5, 4),
    new move("Spacial Rend", 5, 4),
    new move("Lunar Dance", 10, 4),
    new move("Crush Grip", 5, 4),
    new move("Magma Storm", 5, 4),
    new move("Dark Void", 10, 4),
    new move("Seed Flare", 5, 4),
    new move("Ominous Wind", 5, 4),
    new move("Shadow Force", 5, 4),
    new move("Hone Claws", 15, 5),
    new move("Wide Guard", 10, 5),
    new move("Guard Split", 10, 5),
    new move("Power Split", 10, 5),
    new move("Wonder Room", 10, 5),
    new move("Psyshock", 10, 5),
    new move("Venoshock", 10, 5),
    new move("Autotomize", 15, 5),
    new move("Rage Powder", 20, 5),
    new move("Telekinesis", 15, 5),
    new move("Magic Room", 10, 5),
    new move("Smack Down", 15, 5),
    new move("Storm Throw", 10, 5),
    new move("Flame Burst", 15, 5),
    new move("Sludge Wave", 10, 5),
    new move("Quiver Dance", 20, 5),
    new move("Heavy Slam", 10, 5),
    new move("Synchronoise", 15, 5),
    new move("Electro Ball", 10, 5),
    new move("Soak", 20, 5),
    new move("Flame Charge", 20, 5),
    new move("Coil", 20, 5),
    new move("Low Sweep", 20, 5),
    new move("Acid Spray", 20, 5),
    new move("Foul Play", 15, 5),
    new move("Simple Beam", 15, 5),
    new move("Entrainment", 15, 5),
    new move("After You", 15, 5),
    new move("Round", 15, 5),
    new move("Echoed Voice", 15, 5),
    new move("Chip Away", 20, 5),
    new move("Clear Smog", 15, 5),
    new move("Stored Power", 10, 5),
    new move("Quick Guard", 15, 5),
    new move("Ally Switch", 15, 5),
    new move("Scald", 15, 5),
    new move("Shell Smash", 15, 5),
    new move("Heal Pulse", 10, 5),
    new move("Hex", 10, 5),
    new move("Sky Drop", 10, 5),
    new move("Shift Gear", 10, 5),
    new move("Circle Throw", 10, 5),
    new move("Incinerate", 15, 5),
    new move("Quash", 15, 5),
    new move("Acrobatics", 15, 5),
    new move("Reflect Type", 15, 5),
    new move("Retaliate", 5, 5),
    new move("Final Gambit", 5, 5),
    new move("Bestow", 15, 5),
    new move("Inferno", 5, 5),
    new move("Water Pledge", 10, 5),
    new move("Fire Pledge", 10, 5),
    new move("Grass Pledge", 10, 5),
    new move("Volt Switch", 20, 5),
    new move("Struggle Bug", 20, 5),
    new move("Bulldoze", 20, 5),
    new move("Frost Breath", 10, 5),
    new move("Dragon Tail", 10, 5),
    new move("Work Up", 30, 5),
    new move("Electroweb", 15, 5),
    new move("Wild Charge", 15, 5),
    new move("Drill Run", 10, 5),
    new move("Dual Chop", 15, 5),
    new move("Heart Stamp", 25, 5),
    new move("Horn Leech", 10, 5),
    new move("Sacred Sword", 20, 5),
    new move("Razor Shell", 10, 5),
    new move("Heat Crash", 10, 5),
    new move("Leaf Tornado", 10, 5),
    new move("Steamroller", 20, 5),
    new move("Cotton Guard", 10, 5),
    new move("Night Daze", 10, 5),
    new move("Psystrike", 10, 5),
    new move("Tail Slap", 10, 5),
    new move("Hurricane", 10, 5),
    new move("Head Charge", 15, 5),
    new move("Gear Grind", 15, 5),
    new move("Searing Shot", 5, 5),
    new move("Techno Blast", 5, 5),
    new move("Relic Song", 10, 5),
    new move("Secret Sword", 10, 5),
    new move("Glaciate", 10, 5),
    new move("Bolt Strike", 5, 5),
    new move("Blue Flare", 5, 5),
    new move("Fiery Dance", 10, 5),
    new move("Freeze Shock", 5, 5),
    new move("Ice Burn", 5, 5),
    new move("Snarl", 15, 5),
    new move("Icicle Crash", 10, 5),
    new move("V-create", 5, 5),
    new move("Fusion Flare", 5, 5),
    new move("Fusion Bolt", 5, 5)
];

var setPP = function(value, col, slot) {
    var pp = document.getElementById("pp-"+col+"-"+slot);
    if (moves[value].gen > 3 && col === 0) { pp.base = 0; }
    else { pp.base = moves[value].pp; }
    pp.synch(true);
};

var getMove = {
    byId: function(value, col, slot) {
        document.getElementById("move"+slot+"Note-"+col).innerText = "";
        if (value >= moves.length) { return "glitch"; }
        else {
            setPP(value, col, slot);
            if (moves[value].gen > 3) { document.getElementById("move"+slot+"Note-"+col).innerText = " *glitch move until sent to gen "+moves[value].gen; }
            return moves[value].name;
        }
    },
    
    byName: function(name, col, slot) {
        var value = "?";
        if (name === "") { value = 0; }
        else {
            for (var a = 0; a < moves.length; a++) {
                if (name.toLowerCase() === moves[a].name.toLowerCase()) {
                    value = a;
                    break;
                }
            }
        }
        
        if (value === "?") {
            document.getElementById("move"+slot+"Note-"+col).innerText = " Attack not found";
            return "abort";
        }
        else {
            setPP(value, col, slot);
            if (moves[value].gen > 3) { document.getElementById("move"+slot+"Note-"+col).innerText = " *glitch move until sent to gen "+moves[value].gen; }
            else { document.getElementById("move"+slot+"Note-"+col).innerText = ""; }
            return value;
        }
    }
};




